<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPPMS.Application\EPPMS.Application.csproj" />
    <ProjectReference Include="..\EPPMS.Infrastructure\EPPMS.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Admin\Dashboard\" />
    <Folder Include="Controllers\User\Dashboard\" />
    <Folder Include="Controllers\User\Tasks\" />
    <Folder Include="Controllers\User\Bug\" />
    <Folder Include="Controllers\User\OngoingTasks\" />
    <Folder Include="Controllers\User\Lookup\" />
    <Folder Include="Controllers\User\Notificatons\" />
    <Folder Include="Controllers\User\Profile\" />
    <Folder Include="Configuration\" />
  </ItemGroup>

</Project>
