<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Configuration\Rules\" />
    <Folder Include="Configuration\ValueObjects\" />
    <Folder Include="Identity\Entities\" />
    <Folder Include="Identity\Enumerations\" />
    <Folder Include="Identity\Rules\" />
    <Folder Include="Identity\ValueObjects\" />
    <Folder Include="ProductManagement\Entities\" />
    <Folder Include="ProductManagement\Enumerations\" />
    <Folder Include="ProductManagement\Rules\" />
    <Folder Include="ProductManagement\ValueObjects\" />
    <Folder Include="Reporting\Rules\" />
    <Folder Include="Reporting\ValueObjects\" />
    <Folder Include="WorkManagement\Entities\" />
    <Folder Include="WorkManagement\Enumerations\" />
    <Folder Include="WorkManagement\Rules\" />
    <Folder Include="WorkManagement\ValueObjects\" />
  </ItemGroup>

</Project>
