<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\ApiClients\ApplicationApiClient.cs" />
    <Compile Remove="Services\ApiClients\FeatureApiClient.cs" />
    <Compile Remove="Services\Application\ApplicationPortalService.cs" />
    <Compile Remove="Services\Application\IApplicationPortalService.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Pages\Dashboard\" />
    <Folder Include="Areas\Identity\" />
    <Folder Include="Areas\Configuration\" />
    <Folder Include="Areas\Dashboard\" />
    <Folder Include="Areas\Reporting\" />
    <Folder Include="Common\" />
    <Folder Include="Middleware\" />
    <Folder Include="Resources\" />
    <Folder Include="Services\Application\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPPMS.Application\EPPMS.Application.csproj" />
    <ProjectReference Include="..\EPPMS.Infrastructure\EPPMS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
